### ISSUE TITLE
License Needed Please

### ISSUE THREAD

**Issue by HassanAmr** [chengyuan/reago-1.1#16]
Hi,

Would you please provide a license so that we can use it bioconda?

Thanks,
Hassan

**Comment by AdamSorrel** [comment]
Hey guys,

This is only vaguely related to this issue, but I want to bring it up and private messages are not available anymore so get back to me either here or on email in my profile @HassanAmr, @chengyuan and @bgruening. 

I have worked a bit on the filter_input.py, changing the user input to implement argparse which is a bit nicer to work with as well as adding comments all over the file to make it a bit easier to understand. There are also a few other bits, like supporting any cm databases and not just the two provided that were hard coded in. 

I think it would be a good idea to add support for other alignment programs beyond cmsearch. I see the advantages, but it's really slow. Since one really just needs the position in the target, query and the strand sense (+ or -), this can be pulled down from any other alignment program as well. I'm probably going to do this for myself so might as well put it out there for other people. 

I would really like to hear from you. I don't mean to meddle with  your code, but it seems that it's not very active lately anyhow and it would be a shame if it went dead. 

Cheers,

Adam

**Comment by bgruening** [comment]
Hi @AdamSorrel!

Great to hear you are working on improving this program. I would encourage you to fork this project and add your changes, open a PR to this repo and hope that someone cares.
What makes it a little bit complicated is that there is no licence information, so in theory you are not allowed to fork it afaik :(

**Comment by bgruening** [comment]
Is in the original publication a license mentioned?

**Comment by AdamSorrel** [comment]
No, there isn't anything there. There is a license to the article that's open source, but that's not covering this. But I did find a corresponding author's email address so if we don't get any answers soon, I'll text him. It really is in their interest to have this going if only for the extra citations they can get.

**Comment by bgruening** [comment]
True, but bioinformatics software ... its a mess and there is no funding in maintaining software. It's sad but this is more the standard than the exception :(

**Comment by AdamSorrel** [comment]
Yeah, but clearly we are quite willing and able. I'm sure we'll sort it out. I can spam Cheng on his email or the corresponding author. It's going to be fine ;-).

**Comment by AdamSorrel** [comment]
By the way, @chengyuan, I have obviously no idea what kind of license you would like to stick on reago. For your convenience I've put here one of the more common ones for open source software and also an easy one to understand (BSD license). You just need to fill in the Institute Name and University Name (it's once in the header and once in the last clause) and insert this at the beginning of both of your programs (reago.py and filter_input.py).
```
#  Software License Agreement (BSD License)
#  
#  Copyright (c) 2017, Chen Gyuan, Institute XXXX,
#  University of XXXX.
#  All rights reserved.
#  
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#  
#   * Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#   * Redistributions in binary form must reproduce the above
#     copyright notice, this list of conditions and the following
#     disclaimer in the documentation and/or other materials provided
#     with the distribution.
#   * Neither the name of the Institute XXXX,
#     University XXXX, nor the names of its contributors may be
#     used to endorse or promote products derived from this software
#     without specific prior written permission.
#  
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
#  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
#  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
#  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
#  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
#  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
#  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
#  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
#  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
#  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
#  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
```

**Comment by AdamSorrel** [comment]
As a next step, I have contacted both the Oxford Journal of Bioinformatics in the matter of licensing their content as well as the corresponding author on the Reago paper. I hope that this will yield some usefulness. 
Good luck to us.

**Comment by AdamSorrel** [comment]
Thanks to @chengyuan for adding the license! 
This issue has been resolved so feel free to close it when you can. 
Thanks,
Adam
